services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && npm run build:render
    staticPublishPath: ./build
    headers:
      - source: "/(.*)"
        headers:
          - key: "X-Frame-Options"
            value: "DENY"
          - key: "X-Content-Type-Options"
            value: "nosniff"
    rewrites:
      - source: "/(.*)"
        destination: "/index.html"